source "http://rubygems.org"

gem 'dm-core'
gem 'dm-migrations'
gem 'dm-validations'
gem 'dm-aggregates'
gem 'dm-timestamps'
gem 'dm-types'
gem 'dm-postgres-adapter'

gem 'rake', '0.9.2.2'
gem 'colored'
gem 'sinatra'
gem 'rack'
gem 'thin'
gem 'sinatra-synchrony',  :require => 'sinatra/synchrony'
gem 'sinatra-flash',      :require => 'sinatra/flash'
gem 'confit',             :require => 'confit/kernel'
gem 'herokuni', :git => 'git://github.com/poeks/herokuni.git'
gem 'oldrelic', :path => '/Users/poeks/work/oldrelic' #:git => 'git://github.com/poeks/oldrelic.git'
gem 'yajl-ruby'
gem 'extlib'
gem 'haml'